pid /home/asp/Projects/reverse-proxy/bench/bench/nginx.pid;
error_log /home/asp/Projects/reverse-proxy/bench/bench/error.log;

events { worker_connections 1024; }

http {
    access_log off;
    client_body_temp_path /home/asp/Projects/reverse-proxy/bench/bench/tmp/client_body;
    proxy_temp_path       /home/asp/Projects/reverse-proxy/bench/bench/tmp/proxy;
    fastcgi_temp_path     /home/asp/Projects/reverse-proxy/bench/bench/tmp/fastcgi;
    uwsgi_temp_path       /home/asp/Projects/reverse-proxy/bench/bench/tmp/uwsgi;
    scgi_temp_path        /home/asp/Projects/reverse-proxy/bench/bench/tmp/scgi;

    server {
        listen 8888;
        location / {
            return 200 "ok\n";
        }
    }
}
